### ISSUE TITLE
Failed to export

### ISSUE THREAD

**Issue by PointPubMedia** [Icinga/icingaweb2-module-pdfexport#12]
## Describe the bug

Having this error when trying to save as PDF

Can't export

#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#6 {main}

## To Reproduce

1. Click on a report, Download, PDF

## Your Environment

* Module version: 
* Dependent module versions: 
* Icinga Web 2 version and modules (System - About):
* Chrome/Chromium version (`google-chrome --version`):
* Web browser and version:
* PHP version used (`php --version`):
* Server operating system and version:

**Comment by dnsmichi** [comment]
Please fill in the versions involved.

Also, ensure that Chrome works, as described here: https://github.com/Icinga/icingaweb2-module-pdfexport/blob/master/doc/70-Troubleshooting.md

**Comment by PointPubMedia** [comment]
Your Environment
Module version: latest version as today
Dependent module versions:
Reporting: 0.9.0
IPL: 0.1.1
PDF Export: 0.9.0
Reporting: 0.9.0
Incubator: 0.1.1
Reactbundle: 0.4.1
Icinga Web 2 version and modules (System - About):
Chrome/Chromium version (google-chrome --version):  74.0.3729.169
Web browser and version: Nginx -> PHP FPM
PHP version used (php --version): 7.2 
Server operating system and version: Debian 9

**Comment by lippserd** [comment]
The default path the Chrome binary is /bin/google-chrome. It may be different in your setup. If you use the master branch, you have the option to configure the binary in the frontend.
