### ISSUE TITLE
do not rely on chrome

### ISSUE THREAD

**Issue by jesusch** [Icinga/icingaweb2-module-pdfexport#13]
I'm very confused that chrome is a dependency to generate a PDF document? oO
There are several Libs that serve this purpose:
https://ourcodeworld.com/articles/read/226/top-5-best-open-source-pdf-generation-libraries-for-php

**Comment by jesusch** [comment]
Any comment why this gets silently closed?

**Comment by dnsmichi** [comment]
It is missing the wontfix label as this decision was made after many iterations. 

You can research this within GitHub if you need more insights.

#4 & https://github.com/Icinga/icingaweb2/issues?utf8=✓&q=is%3Aissue+pdf
