### ISSUE TITLE
Document PHP 7.1 as min requirement or use a 5.6/7.0 compatible version of libmergepdf

### ISSUE THREAD

**Issue by Raboebie** [Icinga/icingaweb2-module-pdfexport#23]
When running an export of a report the webui simply produces a stack trace complaining that Pdfexport::first() is an undefined method. I have all of the dependencies installed and chrome headless is working as expected.

1. Select a report
2. Select dropdown and export as PDF
3. Stack trace is shown

The PDF should be generated.

Uncaught Error: Call to undefined method Icinga\Module\Pdfexport\ProvidedHook\Pdfexport::first() in /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php:118
Stack trace:
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
Icinga/icingaweb2-module-idoreports#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('downloadAction')
Icinga/icingaweb2-module-reporting#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
Icinga/icingaweb2-module-reporting#3 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
Icinga/icingaweb2-module-reporting#4 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
Icinga/icingaweb2-module-reporting#5 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
Icinga/icingaweb2-module-reporting#6 {main}
thrown

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
Icinga/icingaweb2-module-idoreports#8 {main}

![image](https://user-images.githubusercontent.com/4992098/80141109-59c0db80-85a9-11ea-91d5-845f88537b12.png)

* Module version: 0.10.0 reporting, 
* Dependent module versions:  0.9.1 pdfexport, reactbundle v0.6.0, ipl v0.5.0
* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser and version: Version 81.0.4044.122 (Official Build) (64-bit)
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`): PHP 7.0.33-0ubuntu0.16.04.14
* Server operating system and version: Ubuntu 16.04 Server

**Comment by Raboebie** [comment]
Awesome, thanks a lot. Upgrade to php 7.1 and not it all works!

Maybe you should list 7.1 as a dependency.

**Comment by nilmerg** [comment]
Or maybe we don't need the newest version of this library and can still support older versions? :wink:

**Comment by Raboebie** [comment]
I fully agree with you. Would just be nice if the docs said something about which branch/versions work with which releases.
