### ISSUE TITLE
Uncaught Error: Class 'WebSocket\Client' not found

### ISSUE THREAD

**Issue by Optimaximal** [Icinga/icingaweb2-module-pdfexport#24]
## Describe the bug

Cannot export/download PDF report. Icingaweb2 returns the following error:

`Uncaught Error: Class 'WebSocket\Client' not found in /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php:333
Stack trace:
#0 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(288): Icinga\Module\Pdfexport\HeadlessChrome->printToPDF('127.0.0.1:35987', '7e73b0f6-6e9e-4...', Array)
#1 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): Icinga\Module\Pdfexport\HeadlessChrome->Icinga\Module\Pdfexport\{closure}('\nDevTools liste...')
#2 /usr/share/icingaweb2/modules/reactbundle/vendor/react/stream/src/ReadableResourceStream.php(146): Evenement\EventEmitter->emit('data', Array)
#3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(244): React\Stream\ReadableResourceStream->handleData(Resource id #67)
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(211): React\EventLoop\StreamSelectLoop->waitForStreamActivity(9995365)
#5 /u`
`#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}`

CSV and JSON work fine.

## To Reproduce

1. Run Report
2. Click Download > PDF

## Expected behavior

PDF opened/saved.

## Screenshots

![image](https://user-images.githubusercontent.com/4669242/90633648-515a7380-e21e-11ea-8469-53ce16010057.png)

## Your Environment

* Module version: 0.9.1 (cloned from master)
* Icinga Web 2 version and modules (System - About):
Icinga Web 2	2.8.1
director		1.7.2
doc			2.8.1
idoreports	0.9.0
incubator		0.5.0
ipl			0.5.0
monitoring	2.8.1
reactbundle	0.7.0
reporting		0.9.2
* Chrome/Chromium version: Google Chrome 84.0.4147.125
* Web browser and version: Chrome 84.0.4147.125 (Official Build) (64-bit) on Windows 10
* PHP version used: PHP 7.2.24-0ubuntu0.18.04.6
* Server operating system and version: Ubuntu 18.04.5 LTS

**Comment by lippserd** [comment]
Hi,

This could be a dependency problem. Could you please run `composer install` in the pdfexport module directory and report back whether this fixed your issue.

All the best,
Eric

**Comment by nilmerg** [comment]
We had no similar issues in the last months (besides various installations), so I'll close here.
