### ISSUE TITLE
Provide infallible installation instructions

### ISSUE THREAD

**Issue by peter-snr** [Icinga/icingaweb2-module-pdfexport#26]
## Describe the bug

To install this module, **02-Installation.md reads....**

_"Just drop this module to a pdfexport subfolder in your Icinga Web 2 module path."_

Erm.... Which module? where do I get the 'module' from, perhaps you could be a bit more clear.

In order to try and work out how to install I went to https://github.com/Icinga/icingaweb2-module-reactbundle and tried a similar method.

**Comment by nilmerg** [comment]
Hi,

which *module*? The repository you've downloaded/cloned from here.

And now please tell me how we could make this more clear for you. Because for me, having looked at the repository's name, it couldn't be more obvious. :thinking:

**Comment by peter-snr** [comment]
Hi Johannes,

I would suggest instructions like the other modules for icingaweb, here is a sample taken from the installation page for the reactbundle module.

----
**Sample Tarball installation**

MODULE_NAME=reactbundle
MODULE_VERSION=v0.8.0
MODULES_PATH="/usr/share/icingaweb2/modules"
MODULE_PATH="${MODULES_PATH}/${MODULE_NAME}"
RELEASES="https://github.com/Icinga/icingaweb2-module-${MODULE_NAME}/archive"
mkdir "$MODULE_PATH" \
&& wget -q $RELEASES/${MODULE_VERSION}.tar.gz -O - \
   | tar xfz - -C "$MODULE_PATH" --strip-components 1
icingacli module enable "${MODULE_NAME}"

**Sample GIT installation**

MODULE_NAME=reactbundle
MODULE_VERSION=v0.8.0
REPO="https://github.com/Icinga/icingaweb2-module-${MODULE_NAME}"
MODULES_PATH="/usr/share/icingaweb2/modules"
git clone ${REPO} "${MODULES_PATH}/${MODULE_NAME}" --branch "${MODULE_VERSION}"
icingacli module enable "${MODULE_NAME}"

------

I find these instructions infallible ;) and this seems to be the normal standard for IcingaWeb modules.

Hope this helps
Kind regards
Peter Goudman
