### ISSUE TITLE
View pie charts in PDF exports too

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingaweb2-module-pdfexport#3]
While Tcpdf claimed to support SVGs, it seems that dompdf doesn't. While we don't want to create a custom "PNG renderer", we could get this solved by adding an Imagick-based ->toPng() function in our PieChart renderer.

NB: dompdf doesn't handle floating elements well, aligning images might therefore get a little bit tricky.

**Comment by nilmerg** [comment]
Chrome has no problem with svgs, if we'd provide them inline or on disk. Or we try a JS-approach, might now also work. But let's create a new issue then.
