### ISSUE TITLE
DOM to PDF renderer

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2-module-pdfexport#4]
# Options

As already discussed w/ @nilmerg (offline):

## [PhantomJS](http://phantomjs.org/)

* One big pre-build binary which doesn't work OOTB on CentOS 7 (bad LDD paths)
* No working compile instructions

### Benchmark

* On Ubuntu 16.04 w/ 4 cores and 4G RAM
* Up to about 10s per PDF w/ 30 parallel
* Up to about 17s per PDF w/ 50 parallel

```js
const fs = require('fs');
const htmlPdf = require('html-pdf-chrome');

let now = new Date;
console.log(now);

for (let i = 1; i <= 50; ++i) {
	mkPdf(i);
}

function mkPdf(i) {
	htmlPdf.create('https://netways.de', {port: 9222}).then(
		result => {
			fs.writeFile('/vagrant/' + now + '_' + i + '.pdf', new Buffer(result.data, 'base64'), err => {
				console.log(new Date);
				if (err) {
					console.log(err);
				}
			});
		},
		reason => {
			console.log(new Date);
			console.log(reason);
		}
	);
}
```

### Requirements

* Chromium >= 59 (self-packaged?), running headlessly in the background (not neccessarily via PM2)
* Node.js w/ ECMA 7 (RHEL SCL has Node 8) controller process (code similar to the above)

**Comment by Mikesch-mp** [comment]
Why not just use a link to show page in fullscreen and use the browser to save it as pdf. I did it with my module, because nearly all html|php|whatever to pdf dont work as nice as mordern browsers do :)

**Comment by Mikesch-mp** [comment]
Its just an idea :)

[Icinga Web.pdf](https://github.com/Icinga/icingaweb2-module-pdfexport/files/1778579/Icinga.Web.pdf)

Btw you can crontroll a lot of things for printing with css now https://wiki.selfhtml.org/wiki/CSS/Tutorials/Print-CSS

**Comment by lippserd** [comment]
Hi,

It is of course a good idea to improve our print layout. But this will not help us for PDF exports which are scheduled to be automatically rendered and distributed via Web 2. Our future reporting module is a good example which would require this feature.

Cheers,
Eric

**Comment by Mikesch-mp** [comment]
Ohhhh do i hear reporting module ????? Where can i test it? :)

**Comment by Al2Klimov** [comment]
@lippserd If we use a headless Chromium for this, we'd need only one layout – for both printing and PDF exporting.

**Comment by dnsmichi** [comment]
PhantomJS seems not in development anymore.

https://github.com/ariya/phantomjs/issues/15344

**Comment by Thomas-Gelf** [comment]
@dnsmichi: don't worry, it's not going to be used

**Comment by lippserd** [comment]
I close this issue. We stick to Chrome/Chromium for the PDF rendering.
