### ISSUE TITLE
PDF Export stopped working after update of Icinga

### ISSUE THREAD

**Issue by JensBavenmark** [Icinga/icingaweb2-module-pdfexport#43]
## Describe the bug
After update to Icinga Web 2.9.3 and Icinga 2.13.1-1 the PDF export stopped working. All other exports work.
Also if i try to save config for pdfexport in Chrome field (Chrome headless is run on another hosts) I also get an error.

Error code when creating PDF:

Fatal error: Uncaught ErrorException: Uncaught ErrorException: file_get_contents(/public/css/themes/default.less): failed to open stream: No such file or directory in /usr/share/php/Icinga/Web/StyleSheet.php:185 Stack trace: #0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'file_get_conten...', '/usr/share/php/...', 185, Array) #1 /usr/share/php/Icinga/Web/StyleSheet.php(185): file_get_contents('/public/css/the...') #2 /usr/share/php/Icinga/Web/StyleSheet.php(124): Icinga\Web\StyleSheet->collect() #3 /usr/share/php/Icinga/Web/StyleSheet.php(208): Icinga\Web\StyleSheet->__construct() #4 /usr/share/icingaweb2/application/layouts/scripts/pdf.phtml(18): Icinga\Web\StyleSheet::forPdf() #5 /usr/share/php/Icinga/Web/View.php(235): include('/usr/share/icin...') #6 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...') #7 /usr/share/icingaweb2/library/vendor/Zend/Layout.php(786): Zend_View_Abstract->render(NULL) #8 /usr/share/ici in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 259

Error code when saving config:

Uncaught Error: Call to undefined function GuzzleHttp\_idn_uri_convert() in /usr/share/icingaweb2/modules/pdfexport/vendor/guzzlehttp/guzzle/src/Client.php:220
Stack trace:
#0 /usr/share/icingaweb2/modules/pdfexport/vendor/guzzlehttp/guzzle/src/Client.php(155): GuzzleHttp\Client->buildUri(Object(GuzzleHttp\Psr7\Uri), Array)
#1 /usr/share/icingaweb2/modules/pdfexport/vendor/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Client->requestAsync('GET', 'http://10.24.34...', Array)
#2 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(553): GuzzleHttp\Client->request('GET', 'http://10.24.34...')
#3 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(502): Icinga\Module\Pdfexport\HeadlessChrome->jsonVersion('IP TO OTHER HOST', 9222)
#4 /usr/share/icingaweb2/modules/pdfexport/application/forms/ChromeBinaryForm.php(62): Icinga\Module\Pdfexport\HeadlessChrome->getVersion()
#5 /usr/share/icingaweb2/library/vendor/Zend/Validate/Callback.php(159): Icinga\Module\Pdfexport\For

## To Reproduce

1.  Update Icinga and Icinga Web
2.  Try to export hosts as PDF
3.  Try to change config of PDF export 
4. 

## Expected behavior

A PDF export of the content I chosen is created

## Your Environment

* Module version: 0.9.1
* Dependent module versions: PHP - 7.3.29, Icinga Web - 2.9.3, Icinga PHP Thirdparty - 0.10.0, icinga-php-library 0.7.0
* Icinga Web 2 version and modules (System - About): 2.9.3
* Chrome/Chromium version (`google-chrome --version`): Google Chrome 92.0.4515.159
* Web browser and version: Firefox, Chrome new versions
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: CentOS 7

## Additional context

Worked great before update.

**Comment by nilmerg** [comment]
Please try the latest master instead. We'll release a new version this week, it'd be nice to know that you don't have these issues with the master :wink:

**Comment by nilmerg** [comment]
Please re-open if it appears again with the latest release (v0.10.0)
