### ISSUE TITLE
Export dont work on RHEL 7 - Latest Icingaweb2 - Can't export

### ISSUE THREAD

**Issue by lokidaibel** [Icinga/icingaweb2-module-pdfexport#7]
Export dont work on RHEL 7 - Latest Icingaweb2

## Expected Behavior
PDF will be created

## Current Behavior
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#6 {main}

## Possible Solution
???

## Steps to Reproduce (for bugs)
Install chromium
Follow instractions in the Install.md
-> get the error.

## Context
Fresh Installation of the pdfexport module.

## Your Environment

* Module version (System - About): 0.9
* Icinga Web 2 version and modules (System - About): 

businessprocess | 2.0.0
cube | 1.0.1
director | master
doc | 2.6.2
grafana | master
idoreports | 0.9.0
incubator | v0.1.1
ipl | v0.1.1
monitoring | 2.6.2
pdfexport | 0.9.0
reactbundle | v0.4.1
reporting | 0.9.0
setup | 2.6.2
vspheredb | 1.0.3

* Icinga 2 version (`icinga2 --version`): 2.6.2
* Operating System and version: RHEL 7.6
* Webserver, PHP versions: 
php.x86_64                   5.4.16-46.el7                   @rhel-7-server-rpms
php-Icinga.noarch            2.6.2-1.el7.icinga              @LVR_InfoKom_Icinga2_packages-icinga2-com
php-ZendFramework.noarch     1.12.20-1.el7                   @epel
php-ZendFramework-Db-Adapter-Pdo.noarch
php-ZendFramework-Db-Adapter-Pdo-Mysql.noarch
php-ZendFramework-Db-Adapter-Pdo-Pgsql.noarch
php-bcmath.x86_64            5.4.16-46.el7                   @rhel-7-server-optional-rpms
php-cli.x86_64               5.4.16-46.el7                   @rhel-7-server-rpms
php-common.x86_64            5.4.16-46.el7                   @rhel-7-server-rpms
php-fedora-autoloader.noarch 1.0.0-1.el7                     @LVR_InfoKom_RHEL_7_EPEL_EPEL
php-gd.x86_64                5.4.16-46.el7                   @rhel-7-server-rpms
php-intl.x86_64              5.4.16-46.el7                   @rhel-7-server-optional-rpms
php-ldap.x86_64              5.4.16-46.el7                   @rhel-7-server-rpms
php-mbstring.x86_64          5.4.16-46.el7                   @rhel-7-server-optional-rpms
php-mysql.x86_64             5.4.16-46.el7                   @rhel-7-server-rpms
php-pdo.x86_64               5.4.16-46.el7                   @rhel-7-server-rpms
php-pear.noarch              1:1.9.4-21.el7                  @rhel-7-server-rpms
php-pecl-imagick.x86_64      3.4.3-1.el7.remi.5.4            @LVR_InfoKom_RemiRepo_net_RHEL_7_-_Remi-Repo
php-pgsql.x86_64             5.4.16-46.el7                   @rhel-7-server-rpms
php-php-gettext.noarch       1.0.12-1.el7                    @LVR_InfoKom_RHEL_7_EPEL_EPEL
php-process.x86_64           5.4.16-46.el7                   @rhel-7-server-rpms
php-soap.x86_64              5.4.16-46.el7                   @rhel-7-server-rpms
php-tcpdf.noarch             6.2.26-1.el7                    @LVR_InfoKom_RHEL_7_EPEL_EPEL
php-tcpdf-dejavu-sans-fonts.noarch
php-tidy.x86_64              5.4.16-7.el7                    installed
php-xml.x86_64               5.4.16-46.el7                   @rhel-7-server-rpms
php-xmlrpc.x86_64            5.4.16-46.el7                   @rhel-7-server-rpms
phpMyAdmin.noarch            4.4.15.10-3.el7                 @LVR_InfoKom_RHEL_7_EPEL_EPEL
rh-php71.x86_64              1-1.el7                         @rhel-server-rhscl-7-rpms
rh-php71-php.x86_64          7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-cli.x86_64      7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-common.x86_64   7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-fpm.x86_64      7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-gd.x86_64       7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-intl.x86_64     7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-json.x86_64     7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-ldap.x86_64     7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-mbstring.x86_64 7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-mysqlnd.x86_64  7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-pdo.x86_64      7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-pear.noarch     1:1.10.4-1.el7                  @rhel-server-rhscl-7-rpms
rh-php71-php-pgsql.x86_64    7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-process.x86_64  7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-soap.x86_64     7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-xml.x86_64      7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-php-zip.x86_64      7.1.8-1.el7                     @rhel-server-rhscl-7-rpms
rh-php71-runtime.x86_64      1-1.el7                         @rhel-server-rhscl-7-rpms
[root@lim-vt21 modules]# yum list installed|grep httpd
httpd.x86_64                 2.4.6-88.el7                    @rhel-7-server-rpms
httpd-tools.x86_64           2.4.6-88.el7                    @rhel-7-server-rpms
httpd24-httpd.x86_64         2.4.34-7.el7                    @rhel-server-rhscl-7-rpms
httpd24-httpd-tools.x86_64   2.4.34-7.el7                    @rhel-server-rhscl-7-rpms
httpd24-libcurl.x86_64       7.61.1-1.el7                    @rhel-server-rhscl-7-rpms
httpd24-libnghttp2.x86_64    1.7.1-7.el7                     @rhel-server-rhscl-7-rpms
httpd24-runtime.x86_64       1.1-18.el7                      @rhel-server-rhscl-7-rpms

**Comment by dnsmichi** [comment]
You're saying that you've installed `chromium`. I've used `google-chrome-stable` from the documented repos here: https://github.com/Icinga/icingaweb2-module-pdfexport/blob/master/doc/02-Installation.md

Run something like this to verify that you've got the latest supported version of Chrome:

```
[root@icinga2-elastic ~]# /bin/google-chrome-stable --version
Google Chrome 73.0.3683.103
```

**Comment by lokidaibel** [comment]
Jep. Installing latest chrome instead of chromium did the work.
Please adjust the dokumentation cause this is missleading.

**Comment by dnsmichi** [comment]
> Please adjust the dokumentation cause this is missleading.

Which docs version are you referring to?  I have adjusted the docs yesterday afternoon.

**Comment by lokidaibel** [comment]
I mean the: "The module needs Google Chrome or Chromium supporting headless mode."
in the Installation.md.

Sounds like it could would worke also with chromium. Atleast at my installation it doesnt. @dnsmichi

**Comment by dnsmichi** [comment]
I didn't write the initial docs, I'll ask Eric next week about it.

**Comment by TheCry** [comment]
Hi,
i had the same problem under Debian 9.
I'd added 2 symbolic links:
ln -s /usr/bin/google-chrome-stable /bin/google-chrome-stable
ln -s /usr/bin/google-chrome /bin/google-chrome-stable

Now it works
